# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Eclypse-Z7-Master.xdc

# Block Designs: bd/Top/Top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top || ORIG_REF_NAME==Top} -quiet] -quiet

# IP: bd/Top/ip/Top_UART_Receiver_0_0/Top_UART_Receiver_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_UART_Receiver_0_0 || ORIG_REF_NAME==Top_UART_Receiver_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_UART_Command_Interpr_0_0/Top_UART_Command_Interpr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_UART_Command_Interpr_0_0 || ORIG_REF_NAME==Top_UART_Command_Interpr_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_BMC_Checksum_Validat_0_0/Top_BMC_Checksum_Validat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_BMC_Checksum_Validat_0_0 || ORIG_REF_NAME==Top_BMC_Checksum_Validat_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_BMC_DST_Indicator_0_1/Top_BMC_DST_Indicator_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_BMC_DST_Indicator_0_1 || ORIG_REF_NAME==Top_BMC_DST_Indicator_0_1} -quiet] -quiet

# IP: bd/Top/ip/Top_BMC_SRC_Indicator_0_1/Top_BMC_SRC_Indicator_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_BMC_SRC_Indicator_0_1 || ORIG_REF_NAME==Top_BMC_SRC_Indicator_0_1} -quiet] -quiet

# IP: bd/Top/ip/Top_BMC_Type_Indicator_0_1/Top_BMC_Type_Indicator_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_BMC_Type_Indicator_0_1 || ORIG_REF_NAME==Top_BMC_Type_Indicator_0_1} -quiet] -quiet

# IP: bd/Top/ip/Top_BMC_UART_Response_Ge_0_0/Top_BMC_UART_Response_Ge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_BMC_UART_Response_Ge_0_0 || ORIG_REF_NAME==Top_BMC_UART_Response_Ge_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_Debouncer_0_2/Top_Debouncer_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_Debouncer_0_2 || ORIG_REF_NAME==Top_Debouncer_0_2} -quiet] -quiet

# IP: bd/Top/ip/Top_PulseGenerator_0_1/Top_PulseGenerator_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_PulseGenerator_0_1 || ORIG_REF_NAME==Top_PulseGenerator_0_1} -quiet] -quiet

# IP: bd/Top/ip/Top_xlconstant_0_5/Top_xlconstant_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_xlconstant_0_5 || ORIG_REF_NAME==Top_xlconstant_0_5} -quiet] -quiet

# IP: bd/Top/ip/Top_UART_Loader_0_0/Top_UART_Loader_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_UART_Loader_0_0 || ORIG_REF_NAME==Top_UART_Loader_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_PulseGenerator_1_0/Top_PulseGenerator_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_PulseGenerator_1_0 || ORIG_REF_NAME==Top_PulseGenerator_1_0} -quiet] -quiet

# IP: bd/Top/ip/Top_Debouncer_1_0/Top_Debouncer_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_Debouncer_1_0 || ORIG_REF_NAME==Top_Debouncer_1_0} -quiet] -quiet

# IP: bd/Top/ip/Top_UART_Sender_0_0/Top_UART_Sender_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_UART_Sender_0_0 || ORIG_REF_NAME==Top_UART_Sender_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_BMCEncoder_0_0/Top_BMCEncoder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_BMCEncoder_0_0 || ORIG_REF_NAME==Top_BMCEncoder_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_xlconstant_0_8/Top_xlconstant_0_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_xlconstant_0_8 || ORIG_REF_NAME==Top_xlconstant_0_8} -quiet] -quiet

# IP: bd/Top/ip/Top_xlconstant_0_9/Top_xlconstant_0_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_xlconstant_0_9 || ORIG_REF_NAME==Top_xlconstant_0_9} -quiet] -quiet

# IP: bd/Top/ip/Top_EOMDetector_0_0/Top_EOMDetector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_EOMDetector_0_0 || ORIG_REF_NAME==Top_EOMDetector_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_BMCDecoder_0_0/Top_BMCDecoder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_BMCDecoder_0_0 || ORIG_REF_NAME==Top_BMCDecoder_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_Memory_0_0/Top_Memory_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_Memory_0_0 || ORIG_REF_NAME==Top_Memory_0_0} -quiet] -quiet

# XDC: /home/daguilera/Proyectos/Xilinx/ASWE_Terminal_System/ASWE_Terminal_System.gen/sources_1/bd/Top/Top_ooc.xdc
